//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasswordChangeReminder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PasswordChangeReminder.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for matured passwords on startup and remind?.
        /// </summary>
        internal static string pcr_form_cbCheckStartup {
            get {
                return ResourceManager.GetString("pcr_form_cbCheckStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string pcr_form_close {
            get {
                return ResourceManager.GetString("pcr_form_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string pcr_form_days {
            get {
                return ResourceManager.GetString("pcr_form_days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are listed the passwords you set and when they are due to renew:.
        /// </summary>
        internal static string pcr_form_lb_description {
            get {
                return ResourceManager.GetString("pcr_form_lb_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Age.
        /// </summary>
        internal static string pcr_form_lv_age {
            get {
                return ResourceManager.GetString("pcr_form_lv_age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string pcr_form_lv_name {
            get {
                return ResourceManager.GetString("pcr_form_lv_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next change in.
        /// </summary>
        internal static string pcr_form_lv_nextchangein {
            get {
                return ResourceManager.GetString("pcr_form_lv_nextchangein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind every.
        /// </summary>
        internal static string pcr_form_lv_remindevery {
            get {
                return ResourceManager.GetString("pcr_form_lv_remindevery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string pcr_form_today {
            get {
                return ResourceManager.GetString("pcr_form_today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Change Reminder.
        /// </summary>
        internal static string pcr_plugin_name {
            get {
                return ResourceManager.GetString("pcr_plugin_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind changing password every (in days):.
        /// </summary>
        internal static string pcr_pwentry_cb_remind {
            get {
                return ResourceManager.GetString("pcr_pwentry_cb_remind", resourceCulture);
            }
        }
    }
}
